# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3KmEz-l6yeQ_Ia-VbEjnpeW5Q_uqckN
"""

import streamlit as st
import pandas as pd
import openpyxl
import os

st.title("SMT Feeder List Automation Tool")
st.write("Upload your raw Mounter Setup file and Master BOM to generate the final grouped feeder list.")

# File upload widgets
uploaded_feeder = st.file_uploader("Upload Mounter Setup (.csv)", type=["csv"])
uploaded_bom = st.file_uploader("Upload Master BOM (.xlsx, .xls, .csv)", type=["xlsx", "xls", "csv"])

if uploaded_feeder is not None and uploaded_bom is not None:
    if st.button("Generate Final Feeder List"):
        with st.spinner("Processing files... Please wait."):

            # Save uploaded files temporarily to disk so pandas can read them
            feeder_path = "temp_feeder.csv"
            bom_path = "temp_bom.xlsx" if uploaded_bom.name.endswith(('.xlsx', '.XLSX', '.xls')) else "temp_bom.csv"

            with open(feeder_path, "wb") as f:
                f.write(uploaded_get := uploaded_feeder.getbuffer())
            with open(bom_path, "wb") as f:
                f.write(uploaded_bom.getbuffer())

            final_output = "Final_Grouped_Feeder_List_terr.xlsx"

            # --- YOUR COMBINED PIPELINE LOGIC ---
            try:
                df_feeder = pd.read_csv(feeder_path, skiprows=6)
                df_feeder.columns = df_feeder.columns.str.strip()

                column_mapping = {
                    'Slot': 'slot', 'SubSlot': 'subslot', 'Part': 'part number',
                    'Part Description': 'description', 'Supply': 'supply',
                    'Placements': 'placement', 'BOT': 'BOT Placement',
                    'TOP': 'TOP Placement', 'BOT Designators': 'BOT Designators',
                    'TOP Designators': 'TOP Designators'
                }
                existing_columns = {col: column_mapping[col] for col in df_feeder.columns if col in column_mapping}
                df_feeder = df_feeder.rename(columns=existing_columns)

                desired_column_order = ['slot', 'subslot', 'part number', 'description', 'supply', 'placement', 'BOT Placement', 'TOP Placement', 'BOT Designators', 'TOP Designators']
                final_feeder_cols = [col for col in desired_column_order if col in df_feeder.columns]
                df_feeder = df_feeder[final_feeder_cols].copy()

                # Read BOM
                if bom_path.endswith('.csv'):
                    df_bom = pd.read_csv(bom_path, engine='python')
                else:
                    df_bom = pd.read_excel(bom_path)

                df_bom.columns = df_bom.columns.str.strip()
                target_cols = ['Component/Item Code', 'Item Description', 'Group']
                df_bom = df_bom[target_cols].copy()

                df_feeder['part number'] = df_feeder['part number'].astype(str).str.strip()
                df_bom['Component/Item Code'] = df_bom['Component/Item Code'].astype(str).str.strip()

                group_map = df_bom.groupby('Group').apply(
                    lambda x: x[['Component/Item Code', 'Item Description']].to_dict('records')
                ).to_dict()

                part_to_group = dict(zip(df_bom['Component/Item Code'], df_bom['Group']))
                part_to_description = dict(zip(df_bom['Component/Item Code'], df_bom['Item Description']))

                expanded_rows = []
                merge_ranges = []
                current_row_idx = 2

                for _, row in df_feeder.iterrows():
                    part_num = row['part number']
                    group = part_to_group.get(part_num)

                    if pd.notna(group) and group in group_map:
                        members = group_map[group]
                        start_idx = current_row_idx
                        end_idx = start_idx + len(members) - 1
                        if len(members) > 1:
                            merge_ranges.append((start_idx, end_idx))

                        for i, member in enumerate(members):
                            new_row = row.copy()
                            new_row['part number'] = member['Component/Item Code']
                            new_row['description'] = member['Item Description']
                            if i > 0:
                                leader_cols = ['slot', 'subslot', 'supply', 'placement', 'BOT Placement', 'TOP Placement', 'BOT Designators', 'TOP Designators']
                                for col in leader_cols:
                                    if col in new_row:
                                        new_row[col] = ''
                            expanded_rows.append(new_row)
                            current_row_idx += 1
                    else:
                        new_row = row.copy()
                        if part_num in part_to_description:
                            new_row['description'] = part_to_description[part_num]
                        expanded_rows.append(new_row)
                        current_row_idx += 1

                pd.DataFrame(expanded_rows).to_excel(final_output, index=False)

                # Apply openpyxl merging
                wb = openpyxl.load_workbook(final_output)
                ws = wb.active
                headers = [cell.value for cell in ws[1]]
                cols_to_merge = [col_idx for col_idx, h in enumerate(headers, start=1) if h not in ['part number', 'description']]

                for start_row, end_row in merge_ranges:
                    if start_row < end_row:
                        for col_idx in cols_to_merge:
                            ws.merge_cells(start_row=start_row, end_row=end_row, start_column=col_idx, end_column=col_idx)
                wb.save(final_output)

                st.success("Feeder list generated successfully!")

                # Provide a download button for the user
                with open(final_output, "rb") as file:
                    st.download_button(
                        label="Download Final Feeder List",
                        data=file,
                        file_name="Final_Grouped_Feeder_List_terr.xlsx",
                        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                    )
            except Exception as e:
                st.error(f"An error occurred during processing: {e}")